### ISSUE TITLE
关于我的世界 万物可堆叠【All Stackable】mod的反馈

### ISSUE THREAD

**Issue by qingtong03** [LoganDark/fabric-languagehack#2]
大佬，我尝试了一下，打完mod之后，游戏会在弹出mojang的读条界面之前关闭，使用了Fabric的7.2 | 7.8还有10.8三个版本试了一下都是这个样子，请问是我Fabirc版本的问题还是和启动器哪里需要修改一下

**Comment by KrisCris** [comment]
Why would you post under a wrong repo... LOL

**Comment by LoganDark** [comment]
I don't think this is the right repo, dude...

嘿，它看起来像你已经张贴在错误的GitHub库您的评论
